# Laboratory 3

In [30]:
import sklearn.datasets
import numpy as np
def load():
    return sklearn.datasets.load_iris()['data'].T, sklearn.datasets.load_iris()['target']

def to_col(row):
    return row.reshape(row.size, 1)

In [5]:
D,labels = load() # load dataset and labels

In [7]:
mu = D.mean() # mean of all the elements of the dataset, sum of D[i,j]/D.size
mu

3.4644999999999997

In [26]:
mu = D.mean(axis=1) # mean of all the columns of the dataset
# it is a row vector, i have to reshape it to a column vector
mu = to_col(mu)
mu

array([[5.84333333],
       [3.05733333],
       [3.758     ],
       [1.19933333]])

In [45]:
D_centered = D - mu
N = np.shape(D)[1] #150
C = 1/N * np.dot(D_centered, D_centered.T)
print('C = ',C)
print('mu = ',mu)

C =  [[ 0.68112222 -0.04215111  1.26582     0.51282889]
 [-0.04215111  0.18871289 -0.32745867 -0.12082844]
 [ 1.26582    -0.32745867  3.09550267  1.286972  ]
 [ 0.51282889 -0.12082844  1.286972    0.57713289]]
mu =  [[5.84333333]
 [3.05733333]
 [3.758     ]
 [1.19933333]]


In [49]:
s, U = np.linalg.eigh(C) # compute eigenvalues and eigenvectors of C
print('s = ',s) # s are sorted from the smallest to the largest
print('U = ',U) # U is made by row vectors that are the eigenvectors of C

s =  [0.02367619 0.0776881  0.24105294 4.20005343]
U =  [[ 0.31548719  0.58202985  0.65658877 -0.36138659]
 [-0.3197231  -0.59791083  0.73016143  0.08452251]
 [-0.47983899 -0.07623608 -0.17337266 -0.85667061]
 [ 0.75365743 -0.54583143 -0.07548102 -0.3582892 ]]


In [54]:
P1 = U[:, ::-1] #[:, 0:m]
m=2
P1[:, 0:m]

array([[-0.36138659,  0.65658877],
       [ 0.08452251,  0.73016143],
       [-0.85667061, -0.17337266],
       [-0.3582892 , -0.07548102]])

In [55]:
N

150